// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpcwKxo-cARdTInztVI91LJWsg18fvrU',
    appId: '1:529664438735:web:67a200197a7566c935e2ba',
    messagingSenderId: '529664438735',
    projectId: 'side-by-side-25dc9',
    authDomain: 'side-by-side-25dc9.firebaseapp.com',
    storageBucket: 'side-by-side-25dc9.appspot.com',
    measurementId: 'G-V0PKT9KXEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhNDmznlAb1Qs_JQ6MwBSHx6xjmltK-c',
    appId: '1:529664438735:android:80c5871c29e7833935e2ba',
    messagingSenderId: '529664438735',
    projectId: 'side-by-side-25dc9',
    storageBucket: 'side-by-side-25dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgp-RsLSBbOSVQPNriVGXIeWVyzOdl4o',
    appId: '1:529664438735:ios:1972628cfaef983535e2ba',
    messagingSenderId: '529664438735',
    projectId: 'side-by-side-25dc9',
    storageBucket: 'side-by-side-25dc9.appspot.com',
    iosBundleId: 'com.example.sideBySide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgp-RsLSBbOSVQPNriVGXIeWVyzOdl4o',
    appId: '1:529664438735:ios:1972628cfaef983535e2ba',
    messagingSenderId: '529664438735',
    projectId: 'side-by-side-25dc9',
    storageBucket: 'side-by-side-25dc9.appspot.com',
    iosBundleId: 'com.example.sideBySide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCpcwKxo-cARdTInztVI91LJWsg18fvrU',
    appId: '1:529664438735:web:4ad5d7a38472ae2435e2ba',
    messagingSenderId: '529664438735',
    projectId: 'side-by-side-25dc9',
    authDomain: 'side-by-side-25dc9.firebaseapp.com',
    storageBucket: 'side-by-side-25dc9.appspot.com',
    measurementId: 'G-46BRV7K7QL',
  );
}
